# Generated by Django 6.0.2 on 2026-02-12 18:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Fee amount in ₹', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Current payment status', max_length=15)),
                ('due_date', models.DateField(help_text='Payment due date')),
                ('paid_on', models.DateTimeField(blank=True, help_text='When the fee was actually paid (NULL if not paid)', null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash Payment'), ('online', 'Online Payment'), ('cheque', 'Cheque'), ('other', 'Other')], help_text='How the student paid', max_length=15, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Any notes about this payment')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
                ('student', models.ForeignKey(help_text='Student this fee is for', on_delete=django.db.models.deletion.CASCADE, related_name='fee_records', to='users.student')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Admin who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_records_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Amount actually paid in this transaction', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('cash', 'Cash Payment'), ('online', 'Online Payment'), ('cheque', 'Cheque'), ('other', 'Other')], help_text='Payment method for this transaction', max_length=15)),
                ('reference_id', models.CharField(blank=True, help_text='Online transaction ID or check number', max_length=100)),
                ('paid_on', models.DateTimeField(auto_now_add=True, help_text='When this payment was received')),
                ('receipt_number', models.CharField(blank=True, help_text='Generated receipt number', max_length=50, unique=True)),
                ('notes', models.TextField(blank=True, help_text='Any additional notes about this payment')),
                ('processed_by', models.ForeignKey(help_text='Admin who processed this payment', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fee_record', models.ForeignKey(help_text='Original fee record this payment is for', on_delete=django.db.models.deletion.CASCADE, related_name='payment_logs', to='payments.feerecord')),
            ],
            options={
                'ordering': ['-paid_on'],
            },
        ),
        migrations.AddIndex(
            model_name='feerecord',
            index=models.Index(fields=['student', 'status'], name='payments_fe_student_c10902_idx'),
        ),
        migrations.AddIndex(
            model_name='feerecord',
            index=models.Index(fields=['due_date', 'status'], name='payments_fe_due_dat_3cc06f_idx'),
        ),
        migrations.AddIndex(
            model_name='feerecord',
            index=models.Index(fields=['created_at'], name='payments_fe_created_6a7f39_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['fee_record', 'paid_on'], name='payments_fe_fee_rec_8352ac_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['paid_on'], name='payments_fe_paid_on_2ba7d0_idx'),
        ),
    ]
