# Generated by Django 6.0.2 on 2026-02-12 18:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('driver', 'Driver'), ('admin', 'Admin')], db_index=True, default='student', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When role was assigned')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last role update')),
                ('user', models.OneToOneField(help_text='User this role is assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='user_role', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(help_text='Driver license number', max_length=25, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Phone must be 10 digits')])),
                ('is_verified', models.BooleanField(db_index=True, default=False, help_text='Whether driver is verified')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether driver is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When driver profile was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last profile update')),
                ('assigned_route', models.ForeignKey(blank=True, help_text='Currently assigned route', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='transport.route')),
                ('user', models.OneToOneField(help_text='Link to Django User account', on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['assigned_route'], name='users_drive_assigne_52476c_idx'), models.Index(fields=['is_active'], name='users_drive_is_acti_d6e08c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_ticket', models.CharField(help_text='Unique student ID/Hall ticket number', max_length=20, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Phone must be 10 digits')])),
                ('is_verified', models.BooleanField(db_index=True, default=False, help_text='Whether student email/phone is verified')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When student profile was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last profile update')),
                ('active_route', models.ForeignKey(blank=True, help_text='Currently assigned route', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='transport.route')),
                ('user', models.OneToOneField(help_text='Link to Django User account', on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['active_route'], name='users_stude_active__5b7046_idx'), models.Index(fields=['is_verified'], name='users_stude_is_veri_e47e89_idx')],
            },
        ),
    ]
