# Generated by Django 5.2.6 on 2025-12-11 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0002_alter_student_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='busapp.route'),
        ),
    ]
