# Generated by Django 6.0.2 on 2026-02-12 18:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transport', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(help_text='Current GPS latitude', validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(help_text='Current GPS longitude', validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('speed', models.FloatField(blank=True, help_text='Current speed in km/h', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('heading', models.FloatField(blank=True, help_text='Current direction (0-360 degrees)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)])),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Whether bus is currently active/running')),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True, help_text='When location was last updated')),
                ('current_stop', models.ForeignKey(blank=True, help_text='Stop bus is currently at or near', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_at', to='transport.stop')),
                ('driver', models.ForeignKey(blank=True, help_text='Driver currently operating this route', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_tracking', to='users.driver')),
                ('route', models.OneToOneField(help_text='Route being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='bus_tracker', to='transport.route')),
            ],
            options={
                'verbose_name_plural': 'Bus Trackers',
            },
        ),
        migrations.CreateModel(
            name='GPSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(help_text='GPS latitude (-90 to 90)', validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(help_text='GPS longitude (-180 to 180)', validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('accuracy', models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True)),
                ('speed', models.FloatField(blank=True, help_text='Speed in km/h', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('heading', models.FloatField(blank=True, help_text='Direction in degrees (0-360)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)])),
                ('timestamp', models.DateTimeField(help_text='When location was recorded (device time)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When record was stored in database')),
                ('driver', models.ForeignKey(help_text='Driver operating the bus', on_delete=django.db.models.deletion.CASCADE, related_name='location_logs', to='users.driver')),
                ('route', models.ForeignKey(help_text='Route being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='location_logs', to='transport.route')),
            ],
            options={
                'verbose_name_plural': 'GPS Logs',
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
                'indexes': [models.Index(fields=['driver', 'timestamp'], name='tracking_gp_driver__ba1f5d_idx'), models.Index(fields=['route', 'timestamp'], name='tracking_gp_route_i_08050b_idx'), models.Index(fields=['created_at'], name='tracking_gp_created_43a176_idx')],
            },
        ),
        migrations.CreateModel(
            name='LocationError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('signal_lost', 'GPS Signal Lost'), ('invalid_coords', 'Invalid Coordinates'), ('accuracy_low', 'Low Accuracy'), ('timeout', 'Location Timeout'), ('permission_denied', 'Permission Denied'), ('unknown', 'Unknown Error')], help_text='Type of error', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Detailed error message')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When error occurred')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When issue was resolved', null=True)),
                ('is_critical', models.BooleanField(default=False, help_text='Whether this error needs immediate attention')),
                ('tracker', models.ForeignKey(help_text='Bus tracker that had issue', on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='tracking.bustracker')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tracker', 'timestamp'], name='tracking_lo_tracker_c4209d_idx'), models.Index(fields=['is_critical', 'resolved_at'], name='tracking_lo_is_crit_d17572_idx')],
            },
        ),
    ]
