# Generated by Django 6.0.2 on 2026-02-12 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Route name (e.g., 'Hyderabad to Secunderabad')", max_length=255, unique=True)),
                ('bus_number', models.CharField(blank=True, help_text='Bus registration number', max_length=20, null=True, unique=True)),
                ('start_location', models.CharField(help_text='Starting point of route', max_length=255)),
                ('end_location', models.CharField(help_text='Ending point of route', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this route is currently operational')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When route was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last route update')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='transport_r_is_acti_137c8e_idx')],
            },
        ),
        migrations.CreateModel(
            name='RouteSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of week (0=Monday, 6=Sunday)')),
                ('departure_time', models.TimeField(help_text='Departure time from first stop (HH:MM:SS)')),
                ('arrival_time', models.TimeField(help_text='Arrival time at last stop (HH:MM:SS)')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this schedule is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When schedule was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last schedule update')),
                ('route', models.ForeignKey(help_text='Route this schedule applies to', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='transport.route')),
            ],
            options={
                'ordering': ['route', 'day_of_week'],
                'unique_together': {('route', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Stop name (e.g., 'Main Gate', 'Library')", max_length=255)),
                ('latitude', models.FloatField(help_text='GPS latitude coordinate')),
                ('longitude', models.FloatField(help_text='GPS longitude coordinate')),
                ('arrival_time', models.TimeField(blank=True, help_text='Expected arrival time (HH:MM:SS format)', null=True)),
                ('order', models.PositiveIntegerField(help_text='Sequence of stop in route (1, 2, 3...)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When stop was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last stop update')),
                ('route', models.ForeignKey(help_text='Route this stop belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='transport.route')),
            ],
            options={
                'ordering': ['route', 'order'],
                'indexes': [models.Index(fields=['route', 'order'], name='transport_s_route_i_9fb355_idx')],
                'unique_together': {('route', 'order')},
            },
        ),
    ]
